# Generated by Django 3.2.18 on 2023-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags_list',
            field=models.ManyToManyField(blank=True, related_name='tags_list_task', to='api_view.Tag'),
        ),
    ]
